version: "3"

volumes:
 postgres_data:
 static_data:
 media_data:

services:
 db:
    image: postgres:13.0-alpine
    container_name: heilyaura-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

 web:
    build: .
    container_name: heilyaura
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
